# Generated by Django 2.0.4 on 2018-06-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_auto_20180607_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(upload_to='chat_avatar'),
        ),
    ]
