# Generated by Django 2.0.4 on 2018-06-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_auto_20180607_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(default='images/1.png', upload_to='chat_avatar'),
        ),
    ]
