# Generated by Django 2.0.4 on 2018-06-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0013_auto_20180608_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
