# Generated by Django 2.0.4 on 2018-06-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0014_auto_20180608_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
    ]
